### ISSUE TITLE
emacsclient: error accessing socket

### ISSUE THREAD

**Issue by aissat** [trogdoro/xiki#128] opened 2015-02-12 01:17 UTC
For more information about these matters, see the file named COPYING. =~ Emacs 22 ]]
+ unique=4465
+ ERROR='++ emacsclient -s 4465 -e '\''(select-frame (car (last (frame-list))))'\''
emacsclient: can'\''t find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
emacsclient: error accessing socket "4465"'
+ [[ ++ emacsclient -s 4465 -e '(select-frame (car (last (frame-list))))'
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
emacsclient: error accessing socket "4465" != '' ]]
+ emacs -Q --daemon=4465 -nw
+ emacsclient -s 4465 -e '(load "~/xiki/misc/emacs/start_xiki_daemon.el")'
+ save_args_to_files
+ let i=1
+ params_dir=~/xiki/misc/params
+ '[' '!' -d ~/xiki/misc/params ']'
+ '[' 0 -eq 0 ']'
+ echo ''
+ emacsclient -s 4465 -t
emacsclient: connect: Connection refused
emacsclient: error accessing socket "4465"
+ '[' -f /tmp/xiki_go.txt ']'

**Comment by xiki** [comment] 2015-02-16 07:04
This seems to be a duplicate of #129

**Closed** 2015-02-16 07:05 UTC
